### ISSUE TITLE
Better Image/VLO Selection

### ISSUE THREAD

**Issue by TehcJS** [Kneesnap/FrogLord#6]
It'd be nice to be able to batch import or batch select Images and VLO's and import an image to multiple image files at once. You should also add the ability to select either specific images from a VLO, or all images in a VLO, whilst all selected images remain so.

**Comment by Kneesnap** [comment]
I'm not sure what you mean by selecting specific images from a VLO or all images in a VLO. For what purpose would this be for?

As for importing an image, this is tricky, Frogger has memory space allocated for image header data for every single image in the game in the executable. This means it isn't possible to just add another images, but instead a system will need to be made that will allow using existing image slots in the wrong vlos, but there's a lot of headache there because you have to know what images will be loaded in memory at the same time, and which ones won't. I still have yet to think of a proper design for how to make a system which is both user friendly and completely functional.

Either that, or writing something which can change the pointers to that list in the assembly binary, though I would really like to avoid having to do that since we'd have to make that work on every single version, not to mention some are PSX MIPS executables and some are x86 PE executables.

**Comment by TehcJS** [comment]
I'm trying to change every image to one image, but the current method of changing a texture to an image is tedious and impractical. It would be awesome if there were a way to select all of the images and edit the properties of all of them or just a select few.

**Comment by Kneesnap** [comment]
I fail to see a use-case for this besides meme mods. This feature will not be added. If you don't want to do it by hand, it would be trivial to make a slight edit to froglord code to do it on your own.
